---
# tasks file for fspart

- name: Process input variables, adding default values
  ansible.builtin.import_tasks: vars_defaults.yml

- name: Check partition variables
  ansible.builtin.import_tasks: asserts.yml

- name: Install fstrim.timer if not present
  ansible.builtin.package:
    name: util-linux
    state: present
  when: fs_fstrim_timer_enabled

- name: Enable fstrim service
  ansible.builtin.systemd:
    name: fstrim.timer
    enabled: yes
  when: fs_fstrim_timer_enabled

- name: Check crypttab entries
  ansible.builtin.import_tasks: crypttab.yml

- name: Check systemd unit files for each partition with autofix set to true (unit_name != fstab)
  ansible.builtin.include_tasks: systemdmount.yml
  loop: "{{ partitions | selectattr('autofix') | rejectattr('unit_name', 'equalto', 'fstab') | list }}"

- name: Check fstab file for each partition with autofix set to true (unit_name == fstab)
  ansible.builtin.include_tasks: fstab.yml
  loop: "{{ partitions | selectattr('autofix') | selectattr('unit_name', 'equalto', 'fstab') | list }}"

- name: Validate mount points
  ansible.builtin.import_tasks: validate.yml

- name: Fix filesystems permissions
  ansible.builtin.import_tasks: fix_permissions.yml
