---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    fspart_molecule_systemd: >-
      {{ (ansible_facts['service_mgr'] | default('')) == 'systemd' }}
    fs_fstrim_timer_enabled: false
    fs_run_fix_permissions: false
    fs_world_writeable_fix_enabled: false
    fspart_allow_reboot: false
    fspart_log_exception:
      - /var/log/gdm
      - /var/log/journal
      - /var/log/btmp
      - /var/log/lastlog
      - /var/log/wtmp
    partitions:
      - name: /opt/test
        unit_name: fstab
        src: tmpfs
        fstype: tmpfs
        mount_state: "{{ 'mounted' if fspart_molecule_systemd else 'present' }}"
        mount_options:
          - strictatime
          - nodev
          - nosuid
          - noexec
        validate_options: >-
          {{ ['nodev', 'nosuid', 'noexec'] if fspart_molecule_systemd else [] }}
        autofix: true

      - name: /tmp
        unit_name: tmp.mount
        mount_options:
          - mode=1777
          - strictatime
          - nodev
          - nosuid
          - noexec
        validate_options: >-
          {{ ['nodev', 'nosuid', 'noexec'] if fspart_molecule_systemd else [] }}
        autofix: "{{ fspart_molecule_systemd }}"

      - name: /var/tmp
        unit_name: fstab
        src: tmpfs
        fstype: tmpfs
        mount_state: "{{ 'mounted' if fspart_molecule_systemd else 'present' }}"
        mount_options:
          - strictatime
          - nodev
          - nosuid
          - noexec
        validate_options: >-
          {{ ['nodev', 'nosuid', 'noexec'] if fspart_molecule_systemd else [] }}
        autofix: true

      - name: /tmp_dir
        unit_name: tmp_dir.mount
        mount_options:
          - mode=1777
          - strictatime
          - nodev
          - nosuid
          - noexec
        validate_options: >-
          {{ ['nodev', 'nosuid', 'noexec'] if fspart_molecule_systemd else [] }}
        autofix: "{{ fspart_molecule_systemd }}"

  pre_tasks:
    - name: Ensure /etc/fstab exists
      ansible.builtin.file:
        path: /etc/fstab
        state: touch
        modification_time: preserve
        access_time: preserve
        mode: '0644'
        owner: root
        group: root
      tags:
        - fspart
        - config

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
      tags:
        - fspart
        - config
